### ISSUE TITLE
3372h-320 (send-sms) seems like it needs encryption??

### ISSUE THREAD

**Issue by grawsom** [Salamek/huawei-lte-api#119]
Why I'm writing here is because I wanted to use the 3372 in Node-red, and [this one](https://github.com/zinen/node-red-contrib-huawei-router) have made a Node-red package that uses you API - but.

Seems like the 3372h-320 need some encryption when doing some sms stuff, for me it's send-sms.

Maybe [this one](https://github.com/vzakharchenko/huawei-hilink) could help, because the send-sms works with this package, and what I can see is that in the source is some `<nonce>${encrpt}</nonce>` after date in the URL when calling the API.

If I can help some way in testing with my device I'm here :-)

**Comment by Salamek** [comment]
@grawsom well we do support encrypted requests for some endpoints, see:

https://github.com/Salamek/huawei-lte-api/blob/214ddbf4f756f45ca6e9a1e8226de3be879d0ed1/huawei_lte_api/api/DialUp.py#L41-L46

So you may try to modify https://github.com/Salamek/huawei-lte-api/blob/214ddbf4f756f45ca6e9a1e8226de3be879d0ed1/huawei_lte_api/api/Sms.py#L85 to use `is_encrypted=True` and try if that changes anything...


And looks like this is related to https://github.com/Salamek/huawei-lte-api-ts ? i did not implement encryption there yet, so pls try it with this library, and if it works i will port it to TS version.

**Comment by grawsom** [comment]
I'm not that well in i py (not a programmer), but I will try to see if I can get some stuff running. :-)

**Comment by grawsom** [comment]
SUCCES :-)
I did this in windows, but are going to try this on my pi, hopefully tomorrow, as I said I'm no programmer, but Google is my friend.
Installed python 3, did the pip install as described in Readme, then used the send_sms from examples with correct data, and I got "SMS was send succesfully" - and of cause also received on phone.
And did not change anything in the files regarding `is_encrypted=True`

Don't know yet if I can use the py API with modules in Node-Red, but else will I be waiting for the port to TS/js.
So now I can continue my project, and also maybe "zinen" that made the node-red package will happy to.

**Comment by Salamek** [comment]
@grawsom so this library works for you without any mods?

**Comment by grawsom** [comment]
@Salamek  Yes, and I have also just tested on a clean Raspberry installed with (bullseye v. 11) - did test it with the send_sms.py, and device_info.py and working just fine - so looking forward to the TS update :-)

**Comment by Salamek** [comment]
@grawsom ok, that is great and weird since huawei-lte-api-ts should be working for you too (sms code logic should be identical just written in different language)

**Comment by grawsom** [comment]
@Salamek do we have examples in the TS package as in the Python package, maybe I could start there and not what I get from the other - maybe my script was wrong.

**Comment by Salamek** [comment]
@grawsom i have added some examples to TS version just for you see https://github.com/Salamek/huawei-lte-api-ts/tree/master/examples

**Comment by grawsom** [comment]
@Salamek  Device_info.js is working fine, but still get an error with the send_sms.js
I did put in some console.log for argument [2], [3] and [4], so I was sure of the parsing.
Here is log output
Ready
http://admin:admin@192.168.8.1/
+45XXXXXXXX (replaced my phonenumber with XX)
Hello world
ResponseErrorException: 100005: Unknown
    at new ResponseErrorException (/home/pi/.node-red/node_modules/huawei-lte-api/dist/exceptions.js:20:28)
    at Connection.checkResponseStatus (/home/pi/.node-red/node_modules/huawei-lte-api/dist/Connection.js:157:19)
    at /home/pi/.node-red/node_modules/huawei-lte-api/dist/Connection.js:296:54
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 100005

**Comment by Salamek** [comment]
@grawsom hmm there must be something different in request data that your router does no like...

I have tested what is the difference between `Python` and `TypeScript` version:

TypeScript
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<request>
  <Index>-1</Index>
  <Phones>
    <Phone>+420XXXXXXXXX</Phone>
  </Phones>
  <Sca/>
  <Content>Ahoj2</Content>
  <Length>5</Length>
  <Reserved>1</Reserved>
  <Date>2021-12-20 16:25:22</Date>
</request>
```

Python
```xml
<?xml version="1.0" encoding="utf-8"?>
<request>
  <Index>-1</Index>
  <Phones>
    <Phone>+420XXXXXXXXX</Phone>
  </Phones>
  <Sca></Sca>
  <Content>Ahoj2</Content>
  <Length>5</Length>
  <Reserved>1</Reserved>
  <Date>2021-12-20 19:01:33</Date>
</request>
```

So, as you can see there is difference in how `Sca` is handled and some data added in XML header... since Huawei XML parser is shitty AF, it is possible that this is our issue... so lets try to first change `Sca` 

So pls, update to huawei-lte-api-ts 0.0.8 and try again

**Comment by grawsom** [comment]
@Salamek I have now tested  on windows and raspberry - with no luck.
I also played with wireshark to see differences, and I don't think it's the xml header, more to belive the way with credintials.

I have saved files from wireshark, maybe you can get some out of them.

CENSORED URL

I also found an script that works, see if can help someway.

[script.zip](https://github.com/Salamek/huawei-lte-api/files/7757456/script.zip)
